name: 'Terraform Destroy'

on:
  workflow_dispatch:
  # workflow_run:
  #   workflows: ["Terraform Plan and Apply"]
  #   types:
  #     - completed

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      # Download saved plan from artifacts
      - name: Download Terraform Plan
        uses: actions/download-artifact@v2
        with: 
          name: tfplan
          path: .
      
      # Configure Terraform backend
      - name: Configure Terraform Backend
        run: |
          terraform init -backend-config="resource_group_name=StorageRG" -backend-config="storage_account_name=taskboardstoragekris" -backend-config="container_name=taskboardcontainer" -backend-config="key=terraform.tfstate"

      # Terraform Destroy
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
